// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShorteningWebService;

#nullable disable

namespace ShorteningWebService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220523173926_AddBaseComponent")]
    partial class AddBaseComponent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ShorteningWebService.LinkMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shorted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LinkMaps");
                });

            modelBuilder.Entity("ShorteningWebService.LinkMapError", b =>
                {
                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.ToTable("LinkMapErrors");
                });

            modelBuilder.Entity("ShorteningWebService.LinkMapUse", b =>
                {
                    b.Property<Guid>("LinkMapId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("When")
                        .HasColumnType("TEXT");

                    b.HasIndex("LinkMapId");

                    b.ToTable("LinkMapUses");
                });

            modelBuilder.Entity("ShorteningWebService.LinkMapUse", b =>
                {
                    b.HasOne("ShorteningWebService.LinkMap", "LinkMap")
                        .WithMany()
                        .HasForeignKey("LinkMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkMap");
                });
#pragma warning restore 612, 618
        }
    }
}
